### ISSUE TITLE
Las imágenes no se posicionan correctamente en el pdf autogenerado 

### ISSUE THREAD

**Issue by zcc1001** [zcc1001/GESPRO_GESTIONTAREAS#12]

**Comment by asl1006** [comment]
http://stackoverflow.com/questions/24285445/sphinx-to-latex-figure-placement

**Comment by asl1006** [comment]
davidmigloz added a commit that referenced this issue on 20 Jan 2017
@davidmigloz
Fix pdf images position #164

**Comment by asl1006** [comment]
davidmigloz added a commit that referenced this issue on 20 Jan 2017
@davidmigloz
Fix images position #164

**Comment by asl1006** [comment]
davidmigloz added a commit that referenced this issue on 20 Jan 2017
@davidmigloz
Fix images position #164

**Comment by asl1006** [comment]
davidmigloz added a commit that referenced this issue on 20 Jan 2017
@davidmigloz
Fix images position #164

**Comment by asl1006** [comment]
davidmigloz added a commit that referenced this issue on 20 Jan 2017
@davidmigloz
Fix images position #164

**Comment by asl1006** [comment]
davidmigloz added a commit that referenced this issue on 21 Jan 2017
@davidmigloz
Fix images position #164

**Comment by asl1006** [comment]
davidmigloz added a commit that referenced this issue on 21 Jan 2017
@davidmigloz
Fix images position #164

**Comment by asl1006** [comment]
davidmigloz added a commit that referenced this issue on 21 Jan 2017
@davidmigloz
Fix images position #164
