### ISSUE TITLE
Publicar en Google Play

### ISSUE THREAD

**Issue by asl1006** [zcc1001/GESPRO_GESTIONTAREAS#25]
https://support.google.com/googleplay/android-developer/answer/113469#privacy

https://www.raywenderlich.com/122114/android-app-distribution-tutorial-zero-google-play-store

**Comment by zcc1001** [comment]
![image](https://user-images.githubusercontent.com/94805927/142942004-41b721f2-cea1-4efd-b811-5ef4739e94ae.png)

**Comment by zcc1001** [comment]
https://play.google.com/store/apps/details?id=com.davidmiguel.gobees
