### ISSUE TITLE
Resources$NotFoundException con vectores en Android < 21

### ISSUE THREAD

**Issue by asl1006** [zcc1001/GESPRO_GESTIONTAREAS#29]
https://medium.com/@chrisbanes/appcompat-v23-2-age-of-the-vectors-91cbafa87c88#.u93ttzjpb

**Comment by zcc1001** [comment]
![image](https://user-images.githubusercontent.com/94805927/142943102-483c8e34-5e42-4acf-a742-1d2d34e0a297.png)

**Comment by zcc1001** [comment]
davidmigloz added a commit that referenced this issue on 29 Jan 2017
@davidmigloz
Fix exception with vectors in API < 21 #181
