### ISSUE TITLE
Diseño arquitectónico

### ISSUE THREAD

**Issue by zcc1001** [zcc1001/GESPRO_GESTIONTAREAS#4]

**Comment by asl1006** [comment]
davidmigloz added a commit that referenced this issue on 23 Jan 2017
@davidmigloz
Document Diseno Arquitectonico #150

**Comment by asl1006** [comment]
davidmigloz added a commit that referenced this issue on 23 Jan 2017
@davidmigloz
Add references #150

**Comment by asl1006** [comment]
davidmigloz added a commit that referenced this issue on 24 Jan 2017
@davidmigloz
Improve Diseno Arquitectonico documentation #150
