### ISSUE TITLE
Borrar anterior registro al actualizar el tiempo actual 

### ISSUE THREAD

**Issue by zcc1001** [zcc1001/GESPRO_GESTIONTAREAS#9]

**Comment by asl1006** [comment]
davidmigloz added a commit that referenced this issue on 22 Jan 2017
@davidmigloz
Fix delete old current weather #168

**Comment by asl1006** [comment]
@davidmigloz davidmigloz changed the title Borrar anterior registro al actualiar el tiempo actual Borrar anterior registro al actualizar el tiempo actual on 25 Jan 2017
